#!/bin/sh
#
# Summarize followings from a data file or from stdin
# $ cat data.txt | summarize

tf=$(mktemp)

while IFS= read -r line; do
    echo "$line" >> "$tf"
    lines=$((lines+1))
done < "${1:-/dev/stdin}"

echo "Lines: $lines"
echo "Max: $(max < "$tf")"
echo "Min: $(min < "$tf")"
echo "Total: $(total < "$tf")"
echo ""
echo "Missing:"
gaps < "$tf"
echo ""
echo "Freq:"
freq < "$tf"

rm "$tf"
